
sudo: false
cache:
    directories:
        - "~/.platformio"

#env:
#    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - gem install asciidoctor
    - mkdir out
 
script:
    - asciidoctor -v -d book -D out test.asciidoc
