
sudo: false
cache:
    directories:
        - "~/.platformio"

#env:
#    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - gem install asciidoctor
 
script:
    - asciidoctor -v -d book -D . test.asciidoc
    - asciidoctor -v -d book -D . asciidoc-anleitung.asciidoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
